[tasks.outdated]
workspace = false
command = "cargo"
args = [
	"upgrade", "--locked", "-p", "--dry-run"
]


[tasks.test]
workspace = false
command = "cargo"
args = [
	"test", "--target=x86_64-unknown-linux-gnu", "-p", "tests", "--", "--nocapture"
]
