[tasks.outdated]
workspace = false
command = "cargo"
args = [
	# run `cargo upgrade --dry-run` to check versions defined in [workspace.dependencies]
	"outdated", "-w", "--root-deps-only"
]

[tasks.test]
workspace = false
command = "cargo"
args = [
	"test", "--target=x86_64-unknown-linux-gnu", "-p", "tests", "--", "--nocapture"
]

[tasks.test-player]
workspace = false
command = "cargo"
args = [
	"test", "--target=x86_64-unknown-linux-gnu", "-p", "tests", "--test", "test-player", "--", "--nocapture"
]

[tasks.test-game]
workspace = false
command = "cargo"
args = [
	"test", "--target=x86_64-unknown-linux-gnu", "-p", "tests", "--test", "test-game", "--", "--nocapture"
]
